#!/bin/sh
### BEGIN INIT INFO
# Provides:          simp
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop simp server
### END INIT INFO

export JAVA_HOME=JAVA_HOME=/opt/java
export SIMP_HOME=/opt/servers/simp

case $1 in
    start)
        sh $SIMP_HOME/start.sh
    ;;
    stop)
        sh $SIMP_HOME/stop.sh
    ;;
    *)
    echo "Usage: service simp {start|stop}"
    exit 1
    ;;
esac
exit 0